package com.example.hellovaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class HelloVaadinComposite extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = -830380736412765511L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Label SayHelloLbl;
	@AutoGenerated
	private Button SayHelloBtn;
	@AutoGenerated
	private TextField NameTxtFld;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HelloVaadinComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		SayHelloBtn.addListener(new ClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 8164965161403325122L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				String yourName = (String)NameTxtFld.getValue();
				SayHelloLbl.setValue( "Hello " + yourName );
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("150px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("150px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:20.0px;left:60.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("320px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(true);
		verticalLayout_1.setSpacing(true);
		
		// NameTxtFld
		NameTxtFld = new TextField();
		NameTxtFld.setCaption("Enter your name");
		NameTxtFld.setImmediate(false);
		NameTxtFld.setWidth("-1px");
		NameTxtFld.setHeight("-1px");
		NameTxtFld.setSecret(false);
		verticalLayout_1.addComponent(NameTxtFld);
		
		// SayHelloBtn
		SayHelloBtn = new Button();
		SayHelloBtn.setCaption("Say Hello");
		SayHelloBtn.setImmediate(true);
		SayHelloBtn.setWidth("-1px");
		SayHelloBtn.setHeight("-1px");
		verticalLayout_1.addComponent(SayHelloBtn);
		
		// SayHelloLbl
		SayHelloLbl = new Label();
		SayHelloLbl.setCaption("Say Hello String:");
		SayHelloLbl.setImmediate(false);
		SayHelloLbl.setWidth("-1px");
		SayHelloLbl.setHeight("-1px");
		verticalLayout_1.addComponent(SayHelloLbl);
		
		return verticalLayout_1;
	}

}
